### ISSUE TITLE
java core dump when java.io.tmpdir isn't exist for some unknown reason

### ISSUE THREAD

**Issue by qudongfang** [opentracing-contrib/java-specialagent#143]
The JVM process will core dump when `java.io.tmpdir` doesn't exist for some uncertain reason.

```
futex(0x7efe6c9bf9d0, FUTEX_WAIT, 7786, NULLException in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalStateException: java.nio.file.NoSuchFileException: /export/Packages/publiccloud-drc/latest/tmp/opentracing-specialagent8407658861197114139
	at io.opentracing.contrib.specialagent.SpecialAgentUtil.findJarResources(SpecialAgentUtil.java:434)
	at io.opentracing.contrib.specialagent.SpecialAgent.initialize(SpecialAgent.java:225)
	at io.opentracing.contrib.specialagent.ByteBuddyManager.premain(ByteBuddyManager.java:103)
	at io.opentracing.contrib.specialagent.SpecialAgent.premain(SpecialAgent.java:174)
	... 6 more
Caused by: java.nio.file.NoSuchFileException: /export/Packages/publiccloud-drc/latest/tmp/opentracing-specialagent8407658861197114139
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
	at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
	at java.nio.file.Files.createTempDirectory(Files.java:991)
	at io.opentracing.contrib.specialagent.SpecialAgentUtil.findJarResources(SpecialAgentUtil.java:364)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed
 <unfinished ...>
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)
```

I'm just posting this issue here for reference.

We use `Files.createTempDirectory` in `java-specialagent` which will not create the nonexistent parent directories.
https://github.com/opentracing-contrib/java-specialagent/blob/7c40f4bf15edd284be0293d84df6f356bc920e04/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/SpecialAgent.java#L266-L268

There isn't an API to create all nonexistent parent directories for ```temp``` in JDK  as [Files.createDirectories](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createDirectories-java.nio.file.Path-java.nio.file.attribute.FileAttribute...-) does.

> Creates a directory by creating all nonexistent parent directories first. Unlike the createDirectory method, an exception is not thrown if the directory could not be created because it already exists.

It'll be easier if there is a `Files.createTempDirectories` in JDK.

I am wondering whose responsibility this is.
`java-specialagent`user? The program may work correctly before `java-specialagent`.

Shell we do something about this issue?
Any input is appreciated here.

**Comment by SevaSafris** [comment]
Hi @qudongfang, this is an interesting exception. I'm trying to understand how this can be happening. I think you may need to manually set `java.io.tmpdir` to a path that exists. Looking at the `Files.createTempDirectories` method, I believe it's doing everything correctly.

**Comment by qudongfang** [comment]
Sorry, maybe I am not clear earlier.

We are using [`Files.createTempDirectory`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempDirectory-java.lang.String-java.nio.file.attribute.FileAttribute...-) which will not create the non-exist parent directories in `java-specialagent`.

And there is not an API named `Files.createTempDirectories` in [JDK](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html) which I hope there is.

There will be an `IOException` when we call `Files.createTempDirectory` if `java.io.tmpdir` is a path that does not exist.

Your question is: Why set `java.io.tmpdir` to a non-exist path? Right?

The problem is Tomcat defaults `java.io.tmpdir` to [`$CATALINA_BASE/temp`](https://github.com/apache/tomcat/blob/b724612ef327f1e3c493de44b29ae24e1d757d0f/bin/catalina.sh#L43) and it seems that no one is responsible to make sure `$CATALINA_BASE/temp` exists.

I will dig around further to get the cause of the original exception I got.

**Comment by SevaSafris** [comment]
Hi @qudongfang, thanks for clarifying. I believe it is Catalina's responsibility to create `$CATALINA_BASE/temp`. Because, Catalina sets `java.io.tmpdir` to `$CATALINA_BASE/temp`.

**Comment by qudongfang** [comment]
> I believe it is Catalina's responsibility to create `$CATALINA_BASE/temp`

Yes, you are right.
The responsibility is Catalina's or `java-sepcialagent` users.

My initial point is: Shall we do something to help with this issue?

Here are my points:
1. The user's program may be OK without using `java-sepcialagent` because they may not use `tmp file`.
1. Instead of an Exception or tracing not enabled, `java-sepcialagent` caused the whole jvm crashed.

**Comment by SevaSafris** [comment]
You are absolutely right @qudongfang. I've updated the SpecialAgent to prevent from crashing the VM in case of an exception.

**Comment by qudongfang** [comment]
> I've updated the SpecialAgent to prevent from crashing the VM in case of an exception.

Brilliant!
