### ISSUE TITLE
IllegalThreadStateException when using Static Deferred Attach

### ISSUE THREAD

**Issue by ledor473** [opentracing-contrib/java-specialagent#165]
Hi,

We've tried the `Static Deferred Attach` on a Spring Boot application but the application crash on startup with the following stacktrace:

```
datetime="2019-09-20T15:43:45.152Z" severity="ERROR" logger="SpringApplication" Application run failed Correlation-ID="4a780208-f2b4-46a4-bbab-be2ab9b40291"  
java.lang.IllegalThreadStateException: null
	at java.lang.Thread.start(Thread.java:708)
	at org.springframework.context.event.ContextRefreshedEvent.<init>(ContextRefreshedEvent.java:38)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
	at my.very.own.package.Application.main(Application.java:30)
```

Earlier in the startup, I can also see:
```
Exception in thread "container-0" java.lang.ExceptionInInitializerError
	at io.opentracing.contrib.specialagent.thread.ThreadAgentIntercept.<clinit>(ThreadAgentIntercept.java:39)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer$1.run(TomcatWebServer.java:179)
```

That's not a lot of information but when I applied this change: https://github.com/opentracing-contrib/java-specialagent/pull/164, I get the following stack trace:
```
Exception in thread "container-0" java.lang.ExceptionInInitializerError
	at io.opentracing.contrib.specialagent.thread.ThreadAgentIntercept.<clinit>(ThreadAgentIntercept.java:39)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer$1.run(TomcatWebServer.java:179)
Caused by: java.lang.ClassNotFoundException: io.opentracing.contrib.specialagent.thread.ThreadAgentIntercept
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.opentracing.contrib.specialagent.thread.ThreadAgentIntercept.<clinit>(ThreadAgentIntercept.java:34)
	... 1 more
```

Here's all the Spring deps we use in this project:
```
org.springframework.boot:spring-boot-autoconfigure:jar:2.1.6.RELEASE:compile
org.springframework.boot:spring-boot:jar:2.1.6.RELEASE:compile
org.springframework.boot:spring-boot-actuator:jar:2.1.6.RELEASE:compile
io.springfox:springfox-swagger2:jar:2.8.0:compile
io.springfox:springfox-spi:jar:2.8.0:compile
io.springfox:springfox-core:jar:2.8.0:compile
io.springfox:springfox-schema:jar:2.8.0:compile
io.springfox:springfox-swagger-common:jar:2.8.0:compile
io.springfox:springfox-spring-web:jar:2.8.0:compile
org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE:compile
io.springfox:springfox-swagger-ui:jar:2.8.0:compile
org.springframework.cloud:spring-cloud-context:jar:2.1.0.RELEASE:compile
org.springframework.cloud:spring-cloud-config-client:jar:2.1.0.RELEASE:compile
org.springframework.cloud:spring-cloud-commons:jar:2.1.0.RELEASE:compile
org.springframework.security:spring-security-rsa:jar:1.0.5.RELEASE:compile
org.springframework.security:spring-security-crypto:jar:5.1.5.RELEASE:compile
org.springframework:spring-core:jar:5.1.8.RELEASE:compile
org.springframework:spring-jcl:jar:5.1.8.RELEASE:compile
org.springframework.boot:spring-boot-configuration-processor:jar:2.1.6.RELEASE:compile (optional)
org.springframework.boot:spring-boot-starter-web:jar:2.1.6.RELEASE:compile
org.springframework.boot:spring-boot-starter:jar:2.1.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-logging:jar:2.1.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-json:jar:2.1.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-tomcat:jar:2.1.6.RELEASE:compile
org.springframework:spring-web:jar:5.1.8.RELEASE:compile
org.springframework:spring-beans:jar:5.1.8.RELEASE:compile
org.springframework:spring-webmvc:jar:5.1.8.RELEASE:compile
org.springframework:spring-aop:jar:5.1.8.RELEASE:compile
org.springframework:spring-context:jar:5.1.8.RELEASE:compile
org.springframework:spring-expression:jar:5.1.8.RELEASE:compile
org.springframework.boot:spring-boot-starter-validation:jar:2.1.6.RELEASE:compile
org.springframework.boot:spring-boot-starter-actuator:jar:2.1.6.RELEASE:compile
org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.1.6.RELEASE:compile
```

Also, it's important to note that the application starts successfully **without** `-Dsa.spring`

cc @piclemx

**Comment by piclemx** [comment]
@SevaSafris Should we try wit the `1.4.0` version? Since I saw in another issue that you will cut a new release soon?

**Comment by SevaSafris** [comment]
Hi @ledor473, the Static Deferred Attach mode is not well tested right now. May I ask why you are trying to use Static Deferred Attach instead of Static Attach?

**Comment by ledor473** [comment]
@SevaSafris no particular reason, we saw it in the README and felt it was more appropriate to use it because we use Spring Boot.

**Comment by SevaSafris** [comment]
@ledor473, I had implemented Static Deferred Attach as a workaround for situations where SpecialAgent interfered with Spring during initialization. It is a hack, and clearly does not work in your situation. I aspire to have SpecialAgent be resilient to interference during startup. If you experience such issues, please don't hesitate to open an issue.

**Comment by SevaSafris** [comment]
Hi @ledor473, I have started work on this issue, and have updated the code for the Spring Boot initialization hook. I've removed the `Thread` from the implementation altogether. Please let me know if my changes have not fix this issue.

**Comment by SevaSafris** [comment]
FYI: I have changed the name of the system property for its activation. Before, the property was: `-Dsa.spring`. Now, the property is: `-Dsa.init.defer`. This has been [documented here](https://github.com/opentracing-contrib/java-specialagent/#223-static-deferred-attach).

Also, please note, Static Deferred Attach currently only supports Spring Boot (1.0.0.RELEASE to LATEST), and does not support Spring (i.e. Spring 3, Spring 4, Spring 5, etc).

**Comment by SevaSafris** [comment]
The API for Static Deferred Attach has been formalized in [this issue](https://github.com/opentracing-contrib/java-specialagent/issues/267).
