### ISSUE TITLE
Getting error when using agent with Jetty with a custom ServletFilter

### ISSUE THREAD

**Issue by alvinhom** [opentracing-contrib/java-specialagent#208]
I am trying to instrument an application running with Jetty.  The application has a custom servlet filter in the filter chain to handle some logic.  When I run the application after instrumenting, I am getting the following exception.  I am running the 1.5.1-SNAPSHOT version of the agent, build on my machine.

```
java.lang.NoClassDefFoundError: io/opentracing/contrib/specialagent/EarlyReturnException
        at com.bmc.arsys.restapi.SSOWrapperFilter.doFilter(SSOWrapperFilter.java:57)
        at io.opentracing.contrib.specialagent.rule.servlet.FilterAgentIntercept$1.doFilter(FilterAgentIntercept.java:68)
        at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:180)
        at io.opentracing.contrib.specialagent.rule.servlet.FilterAgentIntercept.doFilter(FilterAgentIntercept.java:65)
        at com.bmc.arsys.restapi.SSOWrapperFilter.doFilter(SSOWrapperFilter.java:45)
        at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
        at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:132)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:740)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:503)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SevaSafris** [comment]
Hi @alvinhom, can you please specify which version of Jetty you are using?

**Comment by alvinhom** [comment]
<jetty.version>9.4.19.v20190610</jetty.version>

**Comment by SevaSafris** [comment]
Hi @alvinhom, can you please provide a log with `-Dsa.log.level=FINER`?

**Comment by alvinhom** [comment]
[sa.log.gz](https://github.com/opentracing-contrib/java-specialagent/files/3818135/sa.log.gz)

**Comment by alvinhom** [comment]
BTW, the application uses OSGI and its classloaders.  According to this Stackoverflow question about OSGI interaction with bytebuddy, classes need to be injected to bootstrap class loader. 

https://stackoverflow.com/questions/43486670/bytebuddy-with-osgi-container

Not sure if this is being handled by SpecialAgent currently.

**Comment by alvinhom** [comment]
I just rebuild from the latest master and the problem went away.  I am guessing it is related to the other fix that you put in for Wildfly.  You can close this issue.  Thanks.

**Comment by SevaSafris** [comment]
Great, thanks for the update.
