### ISSUE TITLE
Dynamic Attach fails to start- java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by maisi** [opentracing-contrib/java-specialagent#288]
Hello, 

I'm trying to attach the specialagent to my application dynamically, the command is:

`java -Xbootclasspath/a:$JAVA_HOME/lib/tools.jar -jar opentracing-specialagent-1.5.2.jar 20984`

it fails to start with the error:

```
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalStateException: Name of -javaagent JAR, which is currently /C:/Users/X/Downloads/opentracing-specialagent-1.5.2.jar, must be: opentracing-specialagent-1.5.2.jar
        at io.opentracing.contrib.specialagent.SpecialAgentUtil.assertJavaAgentJarName(SpecialAgentUtil.java:193)
        at io.opentracing.contrib.specialagent.SpecialAgent.<clinit>(SpecialAgent.java:93)
```

I'm using Windows 10 and Java 1.8.0_231-b11.
Powershell or commandline made no difference.

Any ideas how to solve this?

**Comment by safris** [comment]
Hi @maisi, thank you for bringing our attention to this issue. I have committed a change to attempts to fix this problem. When [this build](https://travis-ci.org/opentracing-contrib/java-specialagent/builds/621215915) completes, please [download the development build](https://github.com/opentracing-contrib/java-specialagent/#2112-development) and try your test again.

**Comment by safris** [comment]
Hi @maisi, we will be releasing SpecialAgent v1.5.3 tomorrow. Can you please confirm whether your issue is resolved?
