### ISSUE TITLE
Java servlet is always creating a new span and finish immediately, not linking child spans

### ISSUE THREAD

**Issue by alvinhom** [opentracing-contrib/java-specialagent#319]
I am running a Jetty application instrumented with Java SpecialAgent.  When using the servlet rules, the application is always creating a new span for a web API and finish it immediately.  The child spans inside the web service call is not being linked to the web service.  E.g.  Svc1 --> DB call,   then SVC1 finishes almost immediately .1ms, and the DB call is not linked with the parent.

I commented out the following line in 
rule/servlet/src/main/java/io/opentracing/contrib/specialagent/rule/servlet/ServletAgentIntercept.java

-      tracingFilter.doFilter((ServletRequest)req, (ServletResponse)res, noopFilterChain);
+      // tracingFilter.doFilter((ServletRequest)req, (ServletResponse)res, noopFilterChain);

then the context is being linked correctly.  I am not sure what the noopFilterChain is doing, but it seems to finish the span of the web service prematurely.

**Comment by safris** [comment]
Hi @alvinhom, thank you for raising this issue. Could you provide further details of your use-case? Specifically, what version of Jetty are you running?

**Comment by alvinhom** [comment]
Looks like Jetty 9.4.12.

**Comment by safris** [comment]
Hi @alvinhom, thanks for the quick response. Jetty 9.4.12 is a version that is below SpecialAgent's lowest tested version of Jetty, which is 7.6.21. Please see the table of supported plugins [here](https://github.com/opentracing-contrib/java-specialagent/#61-instrumentation-plugins) (scroll down to Servlet -> Jetty).

If you desire support from SpecialAgent for Jetty 9.4.12, please create a test repository simulating the error condition of your use-case. I would be able to look at this in detail and provide you with a better assessment as to why this error is happening.

**Comment by safris** [comment]
Hi @alvinhom, I have added Jetty 9.3.28 and 9.4.24 to the versions that are regression tested by SpecialAgent. The regressions are passing, which means that you have a use-case that is outside the scope of our test cases. Could provide a test repo to demonstrate your use-case?

**Comment by alvinhom** [comment]
@safris I just got back from Winter break so it will take me work on this.  The app that I am instrumenting is quite large and uses Jetty and OSGI bundles.  I will try to get the latest version and see if I can reproduce the problem.  If so, I can see if I can produce a test case.

**Comment by safris** [comment]
Hi @alvinhom, we have recently identified issues with the `servlet` rule that relate to this issue. It may be the case that the resolution of the related issues also provides a fix for this issue here. If you could, please download a [development build](https://github.com/opentracing-contrib/java-specialagent/#2112-development) and test your use-case.

**Comment by alvinhom** [comment]
Ok.  I will test it and update here.

**Comment by alvinhom** [comment]
I am getting an error while trying to build from source:

[INFO] Running io.opentracing.contrib.specialagent.rule.thrift.ThriftTest
`isolateClassLoader=false`
All attempts should be taken to avoid setting `isolateClassLoader=false`
io.opentracing.contrib.specialagent.rule.thrift.ThriftProtocolAgentRule
io.opentracing.contrib.specialagent.rule.thrift.ThriftAgentRule
.==============================================================.
|                    Static Deferred Attach                    |
|                        Enabled: false                        |
|==============================================================|
' 0 deferrers were detected
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Received 1
Received 1
Received 0
Received 0
Received 0
Received 0
Received 1
Received 0
Received 1
Received 0
Received 1
Received 1
Received 1
Received 1
Received 1
Received 2
Received 4
[ERROR] Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 24.349 s <<< FAILURE! - in io.opentracing.contrib.specialagent.rule.thrift.ThriftTest
[ERROR] oneWay(io.opentracing.contrib.specialagent.rule.thrift.ThriftTest)  Time elapsed: 15.127 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: io.opentracing.contrib.specialagent.TestUtil.reportedSpansSize Callable expected <2> but was <1> within 15 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:145)
        at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:89)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:902)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:645)
        at io.opentracing.contrib.specialagent.rule.thrift.ThriftTest.oneWay(ThriftTest.java:234)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at io.opentracing.contrib.specialagent.AgentRunner$3.invokeExplosively(AgentRunner.java:587)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at io.opentracing.contrib.specialagent.AgentRunner.run(AgentRunner.java:485)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ThriftTest.oneWay:234 » ConditionTimeout io.opentracing.contrib.specialagent.T...
[INFO] 
[ERROR] Tests run: 13, Failures: 0, Errors: 1, Skipped: 0

**Comment by alvinhom** [comment]
I commented out the Thrift plugin for now since I am not using it.  After that, I was able to test my application and it appears that this problem is fixed.  I am seeing other spans linked with the servlet span.

I am getting some other weird issue though.  I am getting the following exception in one of my service.  I am sure the Servlet does not override init so the ServletConfig should be set by the super class.  But I am getting a NullPointerException.  If you think it is a separate issue, you can close out this one and I can open a new issue.

java.lang.NullPointerException
        at javax.servlet.GenericServlet.getServletContext(GenericServlet.java:123)
        at io.opentracing.contrib.specialagent.rule.servlet.ServletAgentIntercept.getServletContext(ServletAgentIntercept.java:51)
        at io.opentracing.contrib.specialagent.rule.servlet.ServletAgentIntercept.serviceEnter(ServletAgentIntercept.java:63)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:627)
        at com.bmc.rsso.servlet.RssoHttpServlet.service(RssoHttpServlet.java:52)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.bmc.rsso.filter.GZIPFilter.doFilter(GZIPFilter.java:48)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.bmc.rsso.filter.CacheFilter.doFilter(CacheFilter.java:95)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.bmc.rsso.filter.TenantFilter.doFilter(TenantFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.bmc.rsso.filter.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:48)
        at io.opentracing.contrib.specialagent.rule.servlet.FilterAgentIntercept$1.doFilter(FilterAgentIntercept.java:71)
        at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:182)
        at io.opentracing.contrib.specialagent.rule.servlet.FilterAgentIntercept.doFilter(FilterAgentIntercept.java:68)
        at com.bmc.rsso.filter.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:40)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by alvinhom** [comment]
I found the bug in our code.  One of the classes that subclassed the main Servlet class overrode init(Config) without calling super.  I guess the normal path does not try to call getServletContext.  I will close this issue as the original issue is fixed with latest version.  Thanks for investigating it.
