### ISSUE TITLE
Phonon2 JRE-8 error while starting

### ISSUE THREAD

**Issue by rkondra1** [opentracing-contrib/java-specialagent#333]
was using a Java tracking agent to monitor one of our microservices to gather micro-service detailed metrics. But when I am starting “opentracing-specialagent-1.5.4.jar” along with our application I am getting below exception saying need JDK.  Due to the application requirement, we have to use only JRE in containerized photon2 OS.
 
Can you please let me know what has to be done to get the jar running along with our application.
 
 
Application Configuration:
------------------------------------
OS : Linux 4.9.182-3.ph2 #1-photon2
Java : openjre8
 
 
Error:
--------
                Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
                at io.opentracing.contrib.specialagent.SpecialAgent.main(SpecialAgent.java:102)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
                at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by safris** [comment]
Hi @rkondra1, thanks for reporting this exception. We have not considered using only the JRE with SpecialAgent, but let's see if we can make it work. It looks like this error is concerning classes of `tools.jar` not being present on the bootstrap path. The JRE does not come with `tools.jar`.

**Question**: Are you trying to use Dynamic Attach?

If yes, then you must use the JDK, since Dynamic Attach relies on classes present in `tools.jar`.
If no, then there may be something I can do about it.

**Comment by safris** [comment]
Hi @rkondra1, I will close this issue due to inactivity. If you have a subsequent question, don't hesitate to reopen this issue or create a new one.
