### ISSUE TITLE
Reimplement `jdbc` rule via composition pattern

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#341]
The JDBC tracer replaces the connection with a tracing connection with built in tracing stuff, like a wrapper around the entire database connection.

```
connect_1 | java.lang.ClassCastException: io.opentracing.contrib.jdbc.TracingConnection cannot be cast to org.postgresql.core.BaseConnection kafka-connect_1
 at io.debezium.connector.postgresql.TypeRegistry.prime(TypeRegistry.java:312) kafka-connect_1
 at io.debezium.connector.postgresql.TypeRegistry.<init>(TypeRegistry.java:122) kafka-connect_1
 at io.debezium.connector.postgresql.connection.PostgresConnection.<init>(PostgresConnection.java:72) kafka-connect_1
 at io.debezium.connector.postgresql.PostgresConnector.validate(PostgresConnector.java:102) kafka-connect_1
 at >org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:282) kafka-connect_1
```

**Comment by safris** [comment]
Moving this to [v1.5.6](https://github.com/opentracing-contrib/java-specialagent/milestone/3), in favor of a half-step that partially solves the "wrapper problem" in the [JDBC Plugin directly](https://github.com/opentracing-contrib/java-jdbc/pull/59).

**Comment by safris** [comment]
Closing this in lieu of success with #374.

**Comment by safris** [comment]
Reopening due to issue with Debezium:
```
 java.lang.ClassCastException: com.sun.proxy.$Proxy51 cannot be cast to org.postgresql.jdbc.PgConnection
     at io.debezium.connector.postgresql.connection.PostgresConnection.determineDatabaseCharset(PostgresConnection.java:403)
     at io.debezium.connector.postgresql.connection.PostgresConnection.<init>(PostgresConnection.java:73)
     at io.debezium.connector.postgresql.PostgresConnector.validate(PostgresConnector.java:102)
     at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:282)
     at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:537)
     at org.apache.kafka.connect.runtime.distributed.DistributedHerder$6.call(DistributedHerder.java:534)
     at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:270)
     at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:219)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
```

**Comment by randallt** [comment]
I ran into a similar issue, but with the class 'oracle.jdbc.OracleConnection'. A client was trying to set a certain array type, which requires casting to the Oracle connection.

**Comment by safris** [comment]
Hi @randallt, thanks for your feedback. I'm surprised this is happening for `oracle.jdbc.OracleConnection`, because this class is an interface. Can you tell me with which version of SpecialAgent you encountered this issue? Reason I ask is because the patterns utilizing `WrapperProxy` have only been available since v1.5.6, and revised in v1.5.7 (which was just released yesterday).

**Comment by randallt** [comment]
Sorry, my comment was confusing. Disregard. I was using a previous version of the agent before the WrapperProxy was used. Testing with version 1.5.7 fixes the issue.
