### ISSUE TITLE
AgentRunner fail in windows because of file/path separator

### ISSUE THREAD

**Issue by kongzhp** [opentracing-contrib/java-specialagent#384]
In  AssembleUtil.classNameToResource() and AgentRunner.findRulePaths() method, file separator and file path separator are hardcoded as '/' and ':', which only work for linux users. If running test cases in windows, it will fail. Therefore, please use File.separatorChar instead of '/', use File.pathSeparator instead of ':'

**Comment by safris** [comment]
Hi @kongzhp, can you please elaborate on this issue?

1. `AssembleUtil.classNameToResource()` converts a class name to its resource path. This method does not touch the `File` API.
1. `AgentRunner.findRulePaths()` delegates to `SpecialAgentUtil.classPathToFiles()`, which uses `File.separatorChar`.

If you're experiencing issues with `AgentRunner` failing in Windows, can you provide me with the error log?

**Comment by kongzhp** [comment]
Hi Safris,
Thanks for your quick reply.
The exception is:
```
java.lang.AssertionError: 
Expected :io.opentracing.contrib.specialagent.AgentRunner$1@1ce24091
Actual   :sun.misc.Launcher$AppClassLoader@18b4aac2
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.opentracing.contrib.specialagent.AgentRunner.loadClassInIsolatedClassLoader(AgentRunner.java:316)
	at io.opentracing.contrib.specialagent.AgentRunner.<init>(AgentRunner.java:396)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:36)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
I am using specialagent 1.5.6.

I debug this issue, I found that root cause:
In AgentRunner.loadClassInIsolatedClassLoader()
```
final Set<String> testClasses = AgentUtil.getClassFiles(testRulePaths); -> this classes name in testClasses is something like:  this\is\a\class
```
```
            URLClassLoader isolatedClassLoader = new URLClassLoader(AssembleUtil.toURLs(classpath), parent) {
                protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
                    String resourceName = AssembleUtil.classNameToResource(name);
                    if (pluginClasses.contains(resourceName)) {
                        return null;
                    } else {
                        return testClasses.contains(resourceName) ? super.loadClass(name, resolve) : ClassLoader.getSystemClassLoader().loadClass(name);
                    }
                }
            };
```
AssembleUtil.classNameToResource(name) will conver the classname to this/is/a/class

Although this\is\a\class and this/is/a/class refer to the same class , but testClasses.contains(resourceName) will return false, and go to ClassLoader.getSystemClassLoader().loadClass(name), 
And then Assert.assertEquals(isolatedClassLoader, classInClassLoader.getClassLoader()); fail

**Comment by kongzhp** [comment]
In AgentRunner.findRulePaths()
```
    if (isMain) {
      if (logger.isLoggable(Level.FINEST))
        logger.finest("rulePaths of runner will be:\n" + AssembleUtil.toIndentedString(rulePaths));

      System.setProperty(SpecialAgent.RULE_PATH_ARG, AssembleUtil.toString(rulePaths.toArray(), ":"));
    }
```
System.setProperty(SpecialAgent.RULE_PATH_ARG, AssembleUtil.toString(rulePaths.toArray(), ":"));

Colon ':' is not work for windows , so I recommand to use File.pathSeparator as the path separator

**Comment by safris** [comment]
Hi @kongzhp, thank you for digging into this. I have taken your suggestions and have amended the code. Please advise whether the changes resolve the problem you're seeing.

**Comment by kongzhp** [comment]
Hi @safris ,I update my pom.xml to 1.5.7-SNAPSHOT, but I could not find your latest code changes in opentracing-specialagent-1.5.7-20200131.143635-14-tests.jar. Could you please build the 1.5.7-SNAPSHOT and deploy to the maven repo?

**Comment by safris** [comment]
Hi @kongzhp, we have an outstanding problem with the build system. Travis CI is taking ~10 hours to build SpecialAgent, and it usually fails due to issues with Travis. If you wouldn't mind, you can clone the repo and [build SpecialAgent by yourself](https://github.com/opentracing-contrib/java-specialagent#212-for-development). We have an imminent release (as of yesterday), so I will close this issue and will include its changes in the release. If this problem comes up for you again, please don't hesitate to reopen this issue.
