### ISSUE TITLE
Stack-overflow in `FilterAgentIntercept`

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#391]
From [here](https://github.com/opentracing-contrib/java-specialagent/issues/367#issuecomment-580816571):

```
io.opentracing.contrib.specialagent.rule.servlet.FilterAgentIntercept$1.doFilter(FilterAgentIntercept.java:70)
at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:172)
at io.opentracing.contrib.specialagent.rule.servlet.FilterAgentIntercept.doFilter(FilterAgentIntercept.java:67)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:91)
at io.opentracing.contrib.specialagent.rule.servlet.FilterAgentIntercept$1.doFilter(FilterAgentIntercept.java:70)
```

**Comment by safris** [comment]
Marking this issue as closed in lieu of [this fix](https://github.com/opentracing-contrib/java-specialagent/commit/b70c9c4a9f9eb1a6dc6565ce6c5370b4f5b4e18d).
