### ISSUE TITLE
`spring-kafka` failing for jdk8

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#393]
In a number of recent builds, the Spring Kafka integration test has repeatedly failed for jdk8. I believe this is related to the issues we've encountered with Static Deferred Attach for other Spring-based tests, and the fact that it's only failing for jdk8 and not jdk11 is especially surprising. You can refer to [this](https://api.travis-ci.org/v3/job/645086525/log.txt) log, which shows:

```
Spans: [{traceId:1, spanId:2, parentId:0, operationName:"To_users"}, {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}, {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}, {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}]
Span: {traceId:1, spanId:2, parentId:0, operationName:"To_users"}
	Component: java-kafka
	Tags: {component=java-kafka, message_bus.destination=users, span.kind=producer, peer.service=kafka}
	Logs: 
Found "java-kafka" span
Span: {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}
	Component: spring-kafka
	Tags: {span.kind=consumer, component=spring-kafka}
	Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}
	Component: java-kafka
	Tags: {component=java-kafka, message_bus.destination=reply, span.kind=producer, peer.service=kafka}
	Logs: 
Found "java-kafka" span
Span: {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}
	Component: spring-kafka
	Tags: {span.kind=consumer, component=spring-kafka}
	Logs: 
java.lang.AssertionError: 4 spans instead of 6
	at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:114)
	at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:86)
	at io.opentracing.contrib.specialagent.test.spring.kafka.SpringKafkaITest.main(SpringKafkaITest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
```

**Comment by safris** [comment]
Hi @malafeev, this is happening intermittently. I've disabled Static Deferred Attach, and the tests are now passing consistently. Seems that Static Deferred Attach leads to some kind of race condition.

**Comment by safris** [comment]
Hi @malafeev, this is happening again. Here are 6 failures, which show both "2 of 4" and "3 of 4" spans in difference occurrences:

```
Spans: [{traceId:1, spanId:2, parentId:0, operationName:"To_users"}, {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}, {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}, {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}]
Span: {traceId:1, spanId:2, parentId:0, operationName:"To_users"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=users, span.kind=producer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=reply, span.kind=producer, peer.service=kafka}
  Logs: 
-------> Intercept [FixedRateAgentRule@kafka-request-handler-4]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [FixedRateAgentRule@kafka-network-thread-0-ListenerName(PLAINTEXT)-PLAINTEXT-1]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
java.lang.AssertionError: 2 spans instead of 4 of java-kafka
  at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:140)
  at io.opentracing.contrib.specialagent.test.spring.kafka.SpringKafkaITest.main(SpringKafkaITest.java:68)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
```

```
Spans: [{traceId:1, spanId:2, parentId:0, operationName:"To_users"}, {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}, {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}, {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}]
Span: {traceId:1, spanId:2, parentId:0, operationName:"To_users"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=users, span.kind=producer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=reply, span.kind=producer, peer.service=kafka}
  Logs: 
-------> Intercept [FixedRateAgentRule@data-plane-kafka-request-handler-5]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [FixedRateAgentRule@data-plane-kafka-network-thread-0-ListenerName(PLAINTEXT)-PLAINTEXT-0]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [ExecutorAgentRule@ExpirationReaper-0-Fetch]: public void java.util.concurrent.ThreadPoolExecutor.execute(java.lang.Runnable)
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
java.lang.AssertionError: 2 spans instead of 4 of java-kafka
  at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:140)
  at io.opentracing.contrib.specialagent.test.spring.kafka.SpringKafkaITest.main(SpringKafkaITest.java:68)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
```

```
Span: {traceId:1, spanId:2, parentId:0, operationName:"To_users"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=users, span.kind=producer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:5, parentId:4, operationName:"From_reply"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=reply, partition=0, offset=0, span.kind=consumer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:6, parentId:5, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=reply, span.kind=producer, peer.service=kafka}
  Logs: 
-------> Intercept [ExecutorAgentRule@ExpirationReaper-0-Fetch]: public void java.util.concurrent.ThreadPoolExecutor.execute(java.lang.Runnable)
-------> Intercept [FixedRateAgentRule@kafka-request-handler-7]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [FixedRateAgentRule@kafka-network-thread-0-ListenerName(PLAINTEXT)-PLAINTEXT-1]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
java.lang.AssertionError: 3 spans instead of 4 of java-kafka
  at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:140)
  at io.opentracing.contrib.specialagent.test.spring.kafka.SpringKafkaITest.main(SpringKafkaITest.java:68)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
```

```
Spans: [{traceId:1, spanId:2, parentId:0, operationName:"To_users"}, {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}, {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}, {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}]
Span: {traceId:1, spanId:2, parentId:0, operationName:"To_users"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=users, span.kind=producer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=reply, span.kind=producer, peer.service=kafka}
  Logs: 
-------> Intercept [ExecutorAgentRule@ExpirationReaper-0-Fetch]: public void java.util.concurrent.ThreadPoolExecutor.execute(java.lang.Runnable)
-------> Intercept [FixedRateAgentRule@kafka-request-handler-2]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [FixedRateAgentRule@kafka-network-thread-0-ListenerName(PLAINTEXT)-PLAINTEXT-0]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
java.lang.AssertionError: 2 spans instead of 4 of java-kafka
  at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:140)
  at io.opentracing.contrib.specialagent.test.spring.kafka.SpringKafkaITest.main(SpringKafkaITest.java:68)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
```

```
Spans: [{traceId:1, spanId:2, parentId:0, operationName:"To_users"}, {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}, {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}, {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}]
Span: {traceId:1, spanId:2, parentId:0, operationName:"To_users"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=users, span.kind=producer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=reply, span.kind=producer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
-------> Intercept [ExecutorAgentRule@ExpirationReaper-0-Fetch]: public void java.util.concurrent.ThreadPoolExecutor.execute(java.lang.Runnable)
-------> Intercept [FixedRateAgentRule@kafka-request-handler-7]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [FixedRateAgentRule@kafka-network-thread-0-ListenerName(PLAINTEXT)-PLAINTEXT-0]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
java.lang.AssertionError: 2 spans instead of 4 of java-kafka
  at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:140)
  at io.opentracing.contrib.specialagent.test.spring.kafka.SpringKafkaITest.main(SpringKafkaITest.java:68)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
```

```
Spans: [{traceId:1, spanId:2, parentId:0, operationName:"To_users"}, {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}, {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}, {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}]
Span: {traceId:1, spanId:2, parentId:0, operationName:"To_users"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=users, span.kind=producer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=reply, span.kind=producer, peer.service=kafka}
  Logs: 
-------> Intercept [ExecutorAgentRule@ExpirationReaper-0-Fetch]: public void java.util.concurrent.ThreadPoolExecutor.execute(java.lang.Runnable)
-------> Intercept [FixedRateAgentRule@kafka-request-handler-5]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [FixedRateAgentRule@kafka-network-thread-0-ListenerName(PLAINTEXT)-PLAINTEXT-0]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
java.lang.AssertionError: 2 spans instead of 4 of java-kafka
  at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:140)
  at io.opentracing.contrib.specialagent.test.spring.kafka.SpringKafkaITest.main(SpringKafkaITest.java:68)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
```

**Comment by safris** [comment]
@malafeev, I'm reopening this again, because I received an error when running on my local machine. You've spent a while on this already, so let's just keep this issue open and focus on other priorities.

The error I received is:

```
Span: {traceId:1, spanId:2, parentId:0, operationName:"To_users"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=users, span.kind=producer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:3, parentId:2, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
Span: {traceId:1, spanId:4, parentId:3, operationName:"To_reply"}
  Component: java-kafka
  Tags: {component=java-kafka, message_bus.destination=reply, span.kind=producer, peer.service=kafka}
  Logs: 
Span: {traceId:1, spanId:5, parentId:4, operationName:"onMessage"}
  Component: spring-kafka
  Tags: {span.kind=consumer, component=spring-kafka}
  Logs: 
-------> Intercept [ExecutorAgentRule@ExpirationReaper-0-Fetch]: public void java.util.concurrent.ThreadPoolExecutor.execute(java.lang.Runnable)
-------> Intercept [FixedRateAgentRule@kafka-request-handler-2]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [FixedRateAgentRule@kafka-network-thread-0-ListenerName(PLAINTEXT)-PLAINTEXT-2]: public java.util.concurrent.ScheduledFuture java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit)
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
-------> Intercept [ThreadAgentRule@kafka-producer-network-thread | producer-1]: public void java.lang.Thread.run()
java.lang.AssertionError: 2 spans instead of 4 of java-kafka
  at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:139)
  at io.opentracing.contrib.specialagent.test.spring.kafka.SpringKafkaITest.main(SpringKafkaITest.java:68)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
```

**Comment by malafeev** [comment]
@safris issue can be fixed if you put for example
```
TimeUnit.SECONDS.sleep(10);
```
just before this line: https://github.com/opentracing-contrib/java-specialagent/blob/master/test/spring-kafka/spring-kafka-2.2.0/src/test/java/io/opentracing/contrib/specialagent/test/spring/kafka/SpringKafkaITest.java#L111

Problem that 
```
org.apache.kafka.clients.consumer.Consumer.poll(...)
```
method is not intercepted.
and that's super strange because it's not intercepted only for  `Consumer` which is created by Spring Boot.  
but it's intercepted if `Consumer` is manually created.

**Comment by malafeev** [comment]
also that's why spring-messaging is failing for static deferred attach

**Comment by safris** [comment]
@malafeev, I've seen this before. The reason it's not being intercepted for Spring Boot is because Spring does something to the bytecode that invalidates the rule. I saw this happen with my own attempts when trying to implement Static Deferred Attach for Spring Boot itself. It may be necessary to figure out an alternate way to intercept the `Consumer`.

**Comment by malafeev** [comment]
@safris but it starts to intercept this method after several seconds when Spring Boot app up and running. Crazy.
