### ISSUE TITLE
Pulsar Functions integration test failing in Travis

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#418]

**Comment by safris** [comment]
Hi @malafeev, can you take a look at this? The Pulsar Functions test has been failing due to a number of reasons. The latest error (for `2.4.2`) is:
```
java.lang.AssertionError: 16 spans instead of 15
	at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:173)
	at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:82)
	at io.opentracing.contrib.specialagent.test.pulsar.functions.PulsarFunctionsITest.testE2EPulsarFunction(PulsarFunctionsITest.java:160)
	at io.opentracing.contrib.specialagent.test.pulsar.functions.PulsarFunctionsITest.start(PulsarFunctionsITest.java:123)
	at io.opentracing.contrib.specialagent.test.pulsar.functions.PulsarFunctionsITest.main(PulsarFunctionsITest.java:66)
	... 5 more
```

**Comment by malafeev** [comment]
looks like can be closed now
