### ISSUE TITLE
`PulsarClientTest` not working

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#482]
Running a regular build, `PulsarClientTest` gets stuck with this:

```
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ pulsar-client ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.opentracing.contrib.specialagent.rule.pulsar.client.PulsarClientTest
`isolateClassLoader=false`
All attempts should be taken to avoid setting `isolateClassLoader=false`
.==============================================================.
|                    Static Deferred Attach                    |
|                        Enabled: false                        |
|==============================================================|
' 0 deferrers were detected
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
07:38:51.413 [main] ERROR org.apache.bookkeeper.bookie.Journal - Problems reading from /var/folders/zb/xjqqmfc54zq8xhdlq48jbz400000gn/T/bk0test7921588760586974063/current/lastMark (this is okay if it is the first time starting this bookie
07:38:51.814 [main] ERROR org.apache.bookkeeper.bookie.Journal - Problems reading from /var/folders/zb/xjqqmfc54zq8xhdlq48jbz400000gn/T/bk1test2864534642979779404/current/lastMark (this is okay if it is the first time starting this bookie
07:38:51.851 [main] ERROR org.apache.bookkeeper.bookie.Journal - Problems reading from /var/folders/zb/xjqqmfc54zq8xhdlq48jbz400000gn/T/bk2test2216008977912001817/current/lastMark (this is okay if it is the first time starting this bookie
07:38:58.376 [pulsar-41-4] ERROR org.apache.pulsar.common.stats.JvmMetrics - Failed to collect GC stats: java.lang:type=GarbageCollector,name=G1 Young Generation
07:39:00.032 [pulsar-ordered-OrderedExecutor-0-0-EventThread] ERROR org.apache.bookkeeper.proto.checksum.CRC32CDigestManager - Sse42Crc32C is not supported, will use less slower CRC32C implementation.
07:39:00.144 [pulsar-ordered-OrderedExecutor-0-0-EventThread] ERROR org.apache.bookkeeper.proto.checksum.CRC32CDigestManager - Sse42Crc32C is not supported, will use less slower CRC32C implementation.
07:39:10.367 [bookkeeper-io-52-2] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0xa305e477]/43.249.70.22:8882, current state CONNECTING : 
io.netty.channel.ConnectTimeoutException: connection timed out: 43.249.70.22/43.249.70.22:8882
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
07:39:10.367 [bookkeeper-io-52-15] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0xfb22eba4]/43.249.70.22:8882, current state CONNECTING : 
io.netty.channel.ConnectTimeoutException: connection timed out: 43.249.70.22/43.249.70.22:8882
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
07:39:10.372 [bookkeeper-io-52-9] ERROR org.apache.bookkeeper.proto.PerChannelBookieClient - Could not connect to bookie: [id: 0xa2d807ef]/43.249.70.22:8882, current state CONNECTING : 
io.netty.channel.ConnectTimeoutException: connection timed out: 43.249.70.22/43.249.70.22:8882
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

**Comment by safris** [comment]
@malafeev, I'm experiencing the same behavior with `PulsarFunctionsTest`. But, the integration tests are running fine. Is there any way to turn on more detailed logging of the Pulsar/Netty internals?

**Comment by malafeev** [comment]
put log4j2.xml to src/test/resources:

```
<Configuration status="DEBUG">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="debug">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>
```
