### ISSUE TITLE
Add rules for Dubbo 2.6 and 2.7

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#501]
Hi @limfriend, would you be able to implement integration tests for your rule? These can be as simple as a copy+paste of the `AgentRunner` tests into `test/dubbo-*` subdirs.

But, you'd first need to implement the `AgentRunner` tests.

**Comment by limfriend** [comment]
there is a problem that fail to start dubbo with AgentRunner.It work well that run Junit test(DubboTest.java). 
dubbo service uses SPI(Service Provider Interface), it seams to not work well with AgentRunner Test. What do you suggest about this exception?
`
@RunWith(AgentRunner.class)
public class DubboAgentTest {
    @Test
    public void testNormalSpans(final MockTracer tracer) throws Exception {
        //TODO change dubboTest to DubboAgent, there is a problem that fail to start dubbo with AgentRunner.
        MockServer server = new MockServer();
        server.start();
    }
}
`
error message:
`
java.lang.ExceptionInInitializerError
	at io.opentracing.contrib.specialagent.rule.dubbo27.MockServer.<init>(MockServer.java:21)
	at io.opentracing.contrib.specialagent.rule.dubbo27.DubboAgentTest.falsehoodTest(DubboAgentTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at io.opentracing.contrib.specialagent.AgentRunner$3.invokeExplosively(AgentRunner.java:587)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.opentracing.contrib.specialagent.AgentRunner.run(AgentRunner.java:485)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.common.extension.ExtensionFactory, cause: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:482)
	at org.apache.dubbo.common.extension.ExtensionLoader.<init>(ExtensionLoader.java:102)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionLoader(ExtensionLoader.java:124)
	at org.apache.dubbo.config.ServiceConfig.<clinit>(ServiceConfig.java:90)
	... 26 more
Caused by: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.common.extension.ExtensionFactory, cause: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:843)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:478)
	... 29 more
Caused by: java.lang.IllegalStateException: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator.generate(AdaptiveClassCodeGenerator.java:89)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:856)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:852)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:841)
	... 30 more

Exception in thread "DubboShutdownHook" java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.common.extension.ExtensionFactory, cause: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:487)
	at org.apache.dubbo.common.extension.ExtensionLoader.<init>(ExtensionLoader.java:102)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionLoader(ExtensionLoader.java:124)
	at org.apache.dubbo.config.DubboShutdownHook.destroyProtocols(DubboShutdownHook.java:98)
	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:91)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:60)
Caused by: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.common.extension.ExtensionFactory, cause: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:843)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:478)
	at org.apache.dubbo.common.extension.ExtensionLoader.<init>(ExtensionLoader.java:102)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionLoader(ExtensionLoader.java:124)
	at org.apache.dubbo.config.ServiceConfig.<clinit>(ServiceConfig.java:90)
	at io.opentracing.contrib.specialagent.rule.dubbo27.MockServer.<init>(MockServer.java:21)
	at io.opentracing.contrib.specialagent.rule.dubbo27.DubboAgentTest.falsehoodTest(DubboAgentTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at io.opentracing.contrib.specialagent.AgentRunner$3.invokeExplosively(AgentRunner.java:587)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.opentracing.contrib.specialagent.AgentRunner.run(AgentRunner.java:485)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: No adaptive method exist on extension org.apache.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator.generate(AdaptiveClassCodeGenerator.java:89)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:856)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:852)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:841)
	... 30 more

`

**Comment by safris** [comment]
Hi @limfriend, have you tried the `@AgentRunner.Config(isolateClassLoader=false)` annotation described [here](https://github.com/opentracing-contrib/java-specialagent/tree/master/opentracing-specialagent-api#51-configuring-agentrunner)?

**Comment by limfriend** [comment]
... Thank your suggest. It blocked me all day.
I had opened pr #505 .
