### ISSUE TITLE
Classloading problems on Tomcat 8.5.40

### ISSUE THREAD

**Issue by pmaciolek** [opentracing-contrib/java-specialagent#51]
Seems that recent updates have broken something and currently Tomcat fails to start with specialagent. Steps to reproduce:

```
$ JAVA_OPTS="-Dsa.tracer=mock -javaagent:opentracing-specialagent-1.1.0.jar ./bin/catalina.sh start"
```

```
ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/docs]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1135)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1869)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: io/opentracing/contrib/specialagent/webservletfilter/ServletContextAgentRule
        at org.apache.catalina.core.ApplicationContext.<init>(ApplicationContext.java:128)
        at org.apache.catalina.core.StandardContext.getServletContext(StandardContext.java:2295)
        at org.apache.catalina.core.StandardContext.postWorkDirectory(StandardContext.java:6162)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5005)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 10 more
Caused by: java.lang.ClassNotFoundException: io.opentracing.contrib.specialagent.webservletfilter.ServletContextAgentRule
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 15 more
```

**Comment by pmaciolek** [comment]
[catalina-FINEST.log.zip](https://github.com/opentracing-contrib/java-specialagent/files/3107346/catalina-FINEST.log.zip)
Full logs captured o my local box

**Comment by malafeev** [comment]
my first guess is that Spring Boot version you are using is not supported.
could you try 2+ version?

**Comment by SevaSafris** [comment]
@malafeev, how would a version of Spring Boot be "not supported"?

**Comment by pmaciolek** [comment]
If that helps, I did use the plain Tomcat version with no additional apps installed

**Comment by malafeev** [comment]
please ignore my comment, I supposed to comment another issue

**Comment by SevaSafris** [comment]
Hi @pmaciolek, can you try the latest version of SpecialAgent? I have added a potential fix -- it is a stab in the dark, as I do not know your use-case. Nonetheless, I have a hunch it is related to the context of what I changed in 1.1.1-SNAPSHOT. You can get the SpecialAgent JAR via:

```bash
wget -O opentracing-specialagent-LATEST-SNAPSHOT.jar https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.opentracing.contrib.specialagent&a=opentracing-specialagent&v=LATEST
```

**Comment by pmaciolek** [comment]
@SevaSafris thank you for investigating this. I used the `jar` you suggested and now get this:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: io/opentracing/contrib/specialagent/BootLoaderAgent$FindBootstrapResources
	at java.lang.ClassLoader.getBootstrapResources(ClassLoader.java:1276)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1140)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1138)
	at io.opentracing.contrib.specialagent.SpecialAgentUtil.findJarResources(SpecialAgentUtil.java:520)
	at io.opentracing.contrib.specialagent.SpecialAgent.initialize(SpecialAgent.java:197)
	at io.opentracing.contrib.specialagent.ByteBuddyManager.premain(ByteBuddyManager.java:62)
	at io.opentracing.contrib.specialagent.SpecialAgent.premain(SpecialAgent.java:165)
	... 6 more
```

I tried to compile the most recent version from `master` too but the effect was the same as before.

My tomcat version is plain vanilla, to reproduce it I am just downloading the ZIP file with Tomcat and run it without any extra apps installed. It fails on the default config. I am using macOS flavor of JVM:
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
```

I will try to look around it. I think one of the changes with AgentRuleUtil might have made an impact here

**Comment by pmaciolek** [comment]
@SevaSafris I was going through the commit history and doing a bisect search essentially. This one broken things for Tomcat: https://github.com/opentracing-contrib/java-specialagent/commit/bedcc0c57a0b8d7dbf8b0b7bdbbde0ccaedc094b

**Comment by SevaSafris** [comment]
Hi @pmaciolek, thanks for your attention on this. Do you have any idea why [TomcatServletTest](https://github.com/opentracing-contrib/java-specialagent/blob/0a9a9d7757f7c023bf1ef1888f8a6609a4d27ffb/rules/opentracing-specialagent-web-servlet-filter/src/test/java/io/opentracing/contrib/specialagent/webservletfilter/TomcatServletTest.java) works without the problem you're seeing in the plain vanilla Tomcat install?

**Comment by SevaSafris** [comment]
Hi @pmaciolek, I created a test application with vanilla Tomcat. The application threw an error, but it was not the `NoClassDefFoundError ` error you mentioned in this issue. Nonetheless, the error I produced also needed to be fixed. I have pushed a fix for the error produced in my test application, and it is now available in 1.1.1-SNAPSHOT. Would you be able to run your test case against this newest snapshot? Please let me know!

**Comment by pmaciolek** [comment]
Thank you very much @SevaSafris I just rebuilt the project and Tomcat started just fine using the most recent agent version. I will continue testing but it seems that it works perfectly now. I believe it's OK to close the issue now?

**Comment by SevaSafris** [comment]
That's great to hear! Let me know if you run into any other issues. Closing this now.
