### ISSUE TITLE
IsoClassLoader issue

### ISSUE THREAD

**Issue by randallt** [opentracing-contrib/java-specialagent#540]
I have been banging my head a bit with this one. I have a fork of 1.7.0 where I have stripped out many rules and all the tracers. I have my own Wavefront Tracer (not the bundle) included. With my rebasing on v1.7.0 of the specialagent, I had to move my Wavefront Tracer from being implemented as a rule (which I am now seeing wasn't correct) to being properly isolated like the original embedded tracers were.

With that move, however, I am now hitting a classloading issue with the Wavefront Tracer. It is somehow failing to load

```com.fasterxml.jackson.core.Versioned```

even though that class is in the tracer JAR like everything else. However, if the application that the tracing agent is being added to has that class on the classpath, then the error doesn't occur. So somehow, the IsoClassLoader is getting mixed up and excluding classes in the IsoClassLoader and satisfying them by the application classpath.

I'm wondering if this is related to the hack for the Wavefront bundle mentioned in the IsoClassLoader code:

```
...
final Set<String> names = new HashSet<>();
        try {
          AssembleUtil.<Void>forEachClass(isoClassPaths, null, new BiConsumer<String,Void>() {
            @Override
            public void accept(final String name, final Void arg) {
              // FIXME: This is a hack workaround for https://github.com/wavefrontHQ/wavefront-opentracing-bundle-java/issues/17
              if (BootProxyClassLoader.INSTANCE.getResource(name) == null)
                names.add(name);
            }
          });

...
```

**Comment by randallt** [comment]
Full stack trace I get:

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at com.wavefront.sdk.common.Utils.<clinit>(Utils.java:25)
        at com.wavefront.sdk.proxy.WavefrontProxyClient.sendSpan(WavefrontProxyClient.java:355)
        at com.wavefront.opentracing.reporting.WavefrontSpanReporter.send(WavefrontSpanReporter.java:197)
        at com.wavefront.opentracing.reporting.WavefrontSpanReporter.run(WavefrontSpanReporter.java:152)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.Versioned
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 18 more
2020-04-09 16:30:02,772 [wavefrontSpanReporter] WARN  com.wavefront.opentracing.reporting.WavefrontSpanReporter  - Error processing buffer
java.lang.NoClassDefFoundError: Could not initialize class com.wavefront.sdk.common.Utils
        at com.wavefront.sdk.proxy.WavefrontProxyClient.sendSpan(WavefrontProxyClient.java:355)
        at com.wavefront.opentracing.reporting.WavefrontSpanReporter.send(WavefrontSpanReporter.java:197)
        at com.wavefront.opentracing.reporting.WavefrontSpanReporter.run(WavefrontSpanReporter.java:152)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by randallt** [comment]
Line 25 of `com.wavefront.sdk.common.Utils` is

private static final com.fasterxml.jackson.databind.ObjectMapper JSON_PARSER = new com.fasterxml.jackson.databind.ObjectMapper();

**Comment by randallt** [comment]
Hmm, I commented out the line
```
if (BootProxyClassLoader.INSTANCE.getResource(name) == null)
```
and the issue persists. So I guess it is a larger issue.

**Comment by randallt** [comment]
There is something else at play here--when I use the agent on a dummy Java app (just a CPU hog type thing), it seems to work fine. So I'm guessing that something else in the classpath is at play--but isn't that what the isolated classloader is supposed to prevent?

Will get a FINEST log output in both cases.

**Comment by randallt** [comment]
Okay. I have narrowed this down to having jackson-databind-2.9.5.jar on the classpath. You can reproduce it yourself using the standard 1.7.0 special agent build, with the bundled wavefront tracer and against a dummy application with jackson-databind-2.9.5.jar on the classpath (and no other jackson).

Here is the FINEST and verbose classloader log:
[sa.tkt.log](https://github.com/opentracing-contrib/java-specialagent/files/4458413/sa.tkt.log)

**Comment by safris** [comment]
Hi @randallt, I have reproduced your error, and after considerable head spinning, I believe I've figured out the problem. This issue is not related to `IsoClassLoader`, but is related to an anonymous class loader that is instantiated specifically for the Trace Exporter that is being loaded. This happens on [this line](https://github.com/opentracing-contrib/java-specialagent/blob/master/opentracing-adapter/src/main/java/io/opentracing/contrib/specialagent/OpenTracingAdapter.java#L203).

What led me to realize this:...

There are no log entries with `~~~~~~~~ IsoParentClassLoader.` that also mention `com.fasterxml.jackson.core.Versioned`. This means that this class is not being attempted to be resolved via `IsoClassLoader`.

I checked this by changing:

```java
  public IsoClassLoader(final URL[] urls, final ClassLoader parent) {
    super(urls, new IsoParentClassLoader(urls, parent));
  }
```
to
```java
  public IsoClassLoader(final URL[] urls, final ClassLoader parent) {
    super(urls, ClassLoader.getSystemClassLoader());
  }
```
and
```java
  public IsoClassLoader(final URL[] urls, final ClassLoader parent) {
    super(urls, null);
  }
```
and each had the same effect.

Also, in my test app, I added: `Class.forName("com.fasterxml.jackson.core.Versioned")`, which throws a `ClassNotFoundException`. Also, I cannot find `com.fasterxml.jackson.core.Versioned` in the wavefront tracer JAR.

My logs also show:
```java
Caused by: java.util.ServiceConfigurationError: io.opentracing.contrib.tracerresolver.TracerFactory: com.wavefront.opentracing.WavefrontTracerFactory Unable to get public no-arg constructor
```

I looked at the Wavefront codebase, and it seems that it is using FasterXml implicitly (I could not find an explicit maven dependency). When you provide `jackson-databind-2.9.5.jar` on the classpath, some FasterXml class that is used in `new WavefrontTracerFactory()`  is being masked by a class of a new version, with a different signature that requires this `Versioned` class, which does not exist. The anonymous class loader on [this line](https://github.com/opentracing-contrib/java-specialagent/blob/master/opentracing-adapter/src/main/java/io/opentracing/contrib/specialagent/OpenTracingAdapter.java#L203) was allowing resolution of classes against the system class loader. I thereafter explicitly set the parent class loader to `null`.

Please see the diff of the commit for details.

**Comment by randallt** [comment]
I confirm that this small change fixes the issue on my side as well. Thanks for the quick, thoughtful, and detailed response.

**Comment by safris** [comment]
Thank you for bearing with this issue. There were a significant number of changes from v1.6.1 to v1.7.0, and this was definitely a regression. However, in general, v1.7.0 is a significant step forward for SpecialAgent.
