### ISSUE TITLE
`sparkjava` integration test failing

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#560]
```
Spans: [{traceId:1, spanId:2, parentId:0, operationName:"GET"}]
Span: {traceId:1, spanId:2, parentId:0, operationName:"GET"}
	Component: http-url-connection
	Tags: {http.status_code=200, component=http-url-connection, http.url=http://localhost:8085, peer.hostname=localhost, peer.port=8085, http.method=GET}
	Logs: 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.Exec.main(Exec.java:26)
Caused by: java.lang.AssertionError: "java-web-servlet" span not found
	at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:150)
	at io.opentracing.contrib.specialagent.TestUtil.checkSpan(TestUtil.java:101)
	at io.opentracing.contrib.specialagent.test.sparkjava.SparkJavaITest.main(SparkJavaITest.java:52)
	... 5 more
```

Full log [here](https://app.circleci.com/pipelines/github/opentracing-contrib/java-specialagent/110/workflows/33287a9f-1001-45eb-b271-d637229d8593/jobs/587/parallel-runs/0/steps/0-102).

**Comment by safris** [comment]
Here's another log [here](https://app.circleci.com/pipelines/github/opentracing-contrib/java-specialagent/111/workflows/cd22cfcf-c061-430a-a204-9640d5182588/jobs/668/parallel-runs/0/steps/0-102).
