### ISSUE TITLE
Redis Instrumentation is over reaching, PubSub was not accounted for in Lettuce

### ISSUE THREAD

**Issue by boostchicken** [opentracing-contrib/java-specialagent#88]
Not all Redis Async commands have API compatibility.  Specifically PubSub

`2019-06-07 00:44:00.724 ERROR 20380 --- [enerContainer-1] o.s.d.r.l.RedisMessageListenerContainer  : SubscriptionTask aborted with exception:

org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.lang.ClassCastException: class io.opentracing.contrib.redis.lettuce.TracingRedisAsyncCommands cannot be cast to class io.lettuce.core.pubsub.api.async.RedisPubSubAsyncCommands (io.opentracing.contrib.redis.lettuce.TracingRedisAsyncCommands and io.lettuce.core.pubsub.api.async.RedisPubSubAsyncCommands are in unnamed module of loader 'app')
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:53) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:43) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.subscribe(LettuceConnection.java:827) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.eventuallyPerformSubscription(RedisMessageListenerContainer.java:796) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:752) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.ClassCastException: class io.opentracing.contrib.redis.lettuce.TracingRedisAsyncCommands cannot be cast to class io.lettuce.core.pubsub.api.async.RedisPubSubAsyncCommands (io.opentracing.contrib.redis.lettuce.TracingRedisAsyncCommands and io.lettuce.core.pubsub.api.async.RedisPubSubAsyncCommands are in unnamed module of loader 'app')
	at io.lettuce.core.pubsub.StatefulRedisPubSubConnectionImpl.async(StatefulRedisPubSubConnectionImpl.java:86) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.pubsub.StatefulRedisPubSubConnectionImpl.newRedisSyncCommandsImpl(StatefulRedisPubSubConnectionImpl.java:101) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.pubsub.StatefulRedisPubSubConnectionImpl.newRedisSyncCommandsImpl(StatefulRedisPubSubConnectionImpl.java:43) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.StatefulRedisConnectionImpl.<init>(StatefulRedisConnectionImpl.java:73) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.pubsub.StatefulRedisPubSubConnectionImpl.<init>(StatefulRedisPubSubConnectionImpl.java:59) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.RedisClient.newStatefulRedisPubSubConnection(RedisClient.java:639) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.RedisClient.connectPubSubAsync(RedisClient.java:432) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.RedisClient.connectPubSub(RedisClient.java:382) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:107) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.switchToPubSub(LettuceConnection.java:868) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.initSubscription(LettuceConnection.java:872) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.subscribe(LettuceConnection.java:824) ~[spring-data-redis-2.1.8.RELEASE.jar:2.1.8.RELEASE]
	... 3 common frames omitted
`

**Comment by SevaSafris** [comment]
Hi @boostchicken, did the update to the Redis Lettuce Plugin resolve this issue re PubSub? If so, I'd like to close this issue.

**Comment by boostchicken** [comment]
Yup
